//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3viknavinir.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discussion
    {
        public Discussion()
        {
            this.Upvote = new HashSet<Upvote>();
        }
    
        public int Id { get; set; }
        public string comment { get; set; }
        public System.DateTime dateAdded { get; set; }
        public int userID { get; set; }
        public int mediaID { get; set; }
    
        public virtual Media Media { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<Upvote> Upvote { get; set; }
    }
}
