//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3viknavinir.Content
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VERK014_H3Entities1 : DbContext
    {
        public VERK014_H3Entities1()
            : base("name=VERK014_H3Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Discussion> Discussion { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<Media> Media { get; set; }
        public virtual DbSet<Requests> Requests { get; set; }
        public virtual DbSet<Translation> Translation { get; set; }
        public virtual DbSet<TranslationLines> TranslationLines { get; set; }
        public virtual DbSet<Upvote> Upvote { get; set; }
    }
}
