//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3viknavinir.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media
    {
        public Media()
        {
            this.Discussion = new HashSet<Discussion>();
            this.Translation = new HashSet<Translation>();
        }
    
        public int Id { get; set; }
        public string title { get; set; }
        public int yearOfRelease { get; set; }
        public string description { get; set; }
        public int categoryID { get; set; }
        public string posterPath { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Discussion> Discussion { get; set; }
        public virtual ICollection<Translation> Translation { get; set; }
    }
}
