//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3viknavinir.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public Requests()
        {
            this.Upvote1 = new HashSet<Upvote>();
        }
    
        public int Id { get; set; }
        public Nullable<int> upvote { get; set; }
        public System.DateTime dateOfRequest { get; set; }
        public string title { get; set; }
        public int yearOfRelease { get; set; }
        public string imdbID { get; set; }
        public int userID { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ICollection<Upvote> Upvote1 { get; set; }
    }
}
