//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3viknavinir.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class Translation
    {
        public Translation()
        {
            this.TranslationLines = new HashSet<TranslationLines>();
            this.Upvote = new HashSet<Upvote>();
        }
    
        public int Id { get; set; }
        public bool finished { get; set; }
        public int mediaID { get; set; }
        public int languageID { get; set; }
        public int userID { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual ICollection<TranslationLines> TranslationLines { get; set; }
        public virtual ICollection<Upvote> Upvote { get; set; }
    }
}
