//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3viknavinir.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranslationLine
    {
        public int Id { get; set; }
        public int chapterNumber { get; set; }
        public string startTime { get; set; }
        public string endTime { get; set; }
        public string subtitle { get; set; }
        public bool isEditing { get; set; }
        public System.DateTime dateOfSubmission { get; set; }
        public int translationID { get; set; }
    
        public virtual Translation Translation { get; set; }
    }
}
