//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3viknavinir.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upvote
    {
        public int Id { get; set; }
        public int userID { get; set; }
        public Nullable<int> translationID { get; set; }
        public Nullable<int> requestID { get; set; }
        public Nullable<int> discussionID { get; set; }
    
        public virtual Discussion Discussion { get; set; }
        public virtual Requests Requests { get; set; }
        public virtual Translation Translation { get; set; }
        public virtual Users Users { get; set; }
    }
}
